# Habilita o console (Obrigatório para sumir o 404)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurações do Banco
spring.datasource.url=jdbc:h2:mem:streamingdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# API TMDB
tmdb.api.key=2ee5ea1f09603950ffe7cdb7a43be2a4
tmdb.api.url=https://api.themoviedb.org/3

# JWT
api.security.token.secret=4z7C&KjP#v9n!mQ2wE5rT8yU0iO@pA3sD6fG9hJ1kL4z7X0cV3bN6mQ9wE2rT5y
api.security.token.expiration=86400000